### ISSUE TITLE
Use data.gov.au as definitive source of authority info

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#317]
- [ ] Compare lists
- [ ] Update Right To Know from data.gov.au
- [ ] Update data.gov.au's list from Right To Know
- [ ] Work out a way to use data.gov.au as the definitive source

**Comment by mlandauer** [comment]
@kat is actually in the middle of updating authorities. So, I'd hold off doing anything until she weighs in on this. See #312 and #316

**Comment by henare** [comment]
@brfairless please see @mlandauer's comment above.

**Comment by kat** [comment]
There are 112 datasets found for "FOI disclosure log" on data.gov.au so it is not all the authorities we list. These entries were all uploaded/updated 12/12/13 with no amendments since then.
I remember looking at this when I rolled my sleeves up for #312 the other week and found one straight away which was a 404 so I didn't refer to it unless I got stuck (eg ABC FOI page see #312). That may have been bad luck as checking a few others a lot do work. Here's two that don't though, so I wouldn't call it authoritative up to date source for the 112 either.
http://www.iba.gov.au/about-us/information-publication-scheme/information-publication-scheme-disclosure-log/
http://www.aat.gov.au/AboutTheAAT/FreedomOfInformation/DisclosureLog.htm

As for continuing to update authorities information more generally, please dive in - see #312 for progress/where to pick up if you want to dive in.

**Comment by kat** [comment]
Can notify data.gov.au of updates. There's an email address heartily encouraging anyone to tell them about errors and omissions data.gov@finance.gov.au

**Comment by kat** [comment]
@brfairless @henare I just changed the one for the Administrative Appeals Tribunal, so that could be a good first one to let them know about, if either of you would like to follow up with them & /cc contact@righttoknow.org.au and perhaps open a conversation about how we keep a working list going as @henare suggests :-)

**Comment by kat** [comment]
Would be awesome if we could collaborate through github! we could make some changes and see when they're accepted.

**Comment by kat** [comment]
hmm... probably I should have said - dig in! somewhere up above rather than just let you know where I was up to, sorry! please @brfairless or @henare feel free to dig in and work on this also.

**Comment by kat** [comment]
have started a conversation at https://data.gov.au/dataset/list-of-known-foi-disclosure-logs

**Comment by kat** [comment]
data.gov.au confirm they're rolling in the foi-able agencies we list on the site in their next update to their 'list of known foi disclosure logs' dataset - see conversation at https://data.gov.au/dataset/list-of-known-foi-disclosure-logs - the site states they're reviewing this list monthly and the last review was about a month ago so fingers crossed we should see an update fairly soon.

**Comment by kat** [comment]
latest news "DGA_Custodian Mod  kat • 5 hours ago
Hi Kat, thanks again for the suggestion. Just letting you know that we used the list you provided to substantially increase the amount of entries in this dataset.

Kind Regards,
Allan, data.gov.au team."

There are now 155 FOI disclosure logs, but this is a subset of what we need as a dataset for the list of FOI-ables, so I don't think it fits our needs.
