### ISSUE TITLE
Don't ask requesters to classify auto responses from departments

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#323]
Some departments have auto responders. It's really annoying being asked to classify these (and most people don't).

Surely it can't be that hard to put some rules in to ignore those messages or to at least not ask the requester to classify them.

**Comment by benrfairless** [comment]
The logic on how to automatically classify requests over time is currently hard-coded in the [[InfoRequest model|https://github.com/mysociety/alaveteli/blob/master/app/models/info_request.rb]].

(From: https://github.com/mysociety/alaveteli/wiki/Rules-engine-for-statuses)

**Comment by benrfairless** [comment]
@henare this could be harder then it looks. I'm assuming you raised this because of https://www.righttoknow.org.au/request/501

Having a look at the raw email, there is no reference to the Auto-Responder in the email header. I thought you might be able to add some logic to pick up a header or something.

I would be interested to see what the guys at Alaveteli-dev think about this however :)

**Comment by henare** [comment]
Yep, my thoughts exactly mate. It seems like a feature along these lines would be a good inclusion in Alaveteli.

I was thinking of some kind of matching logic like the censor rules. That way each Alaveteli install could add rules that automatically hide and ignore certain incoming messages which would make it much nicer for the user.

**Comment by benrfairless** [comment]
@henare this has now been raised upstream by someone else: https://github.com/mysociety/alaveteli/issues/2045

**Comment by henare** [comment]
Excellent, thanks Ben.
