### ISSUE TITLE
review wording at help/requesting about extensions for ACT

### ISSUE THREAD

**Issue by kat** [openaustralia/righttoknow#419]
An ACT authority can notify requester of 30 day extension from date of original request. 

 (4) The period of 30 days mentioned in subsection (1) (d) must be
extended by 30 days if the agency or Minister to whom the request
was made determines, in writing, that the requirements of
section 26, 27 or 27A make it appropriate to extend the period. 
http://www.legislation.act.gov.au/a/alt_a1989-46co/current/pdf/alt_a1989-46co.pdf

Our description below currently covers this but only because it's very vague, with 'for various reasons' 

"Within 14 days after they receive your request they must give you written acknowledgement and within 30 days they must provide you with either the documents you have asked for or a written decision on your request.

_For various reasons, this timeframe can be extended_. "

**Comment by henare** [comment]
That's also the case Federally. Since there are so many different reasons that the timeframe can be extended I think it's good to remain non-specific. I also think that we don't want to start playing the clock game with authorities and not putting all their rules on our site helps in this regard.

What do you think @kat? What should we change this to?

**Comment by kat** [comment]
ok fair enough @henare
