### ISSUE TITLE
Select authority page: Small spacing and layout differences

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#438]
![select_authority](https://cloud.githubusercontent.com/assets/48945/6659132/542af50c-cbd2-11e4-8a19-b55620344cb8.gif)

**Comment by equivalentideas** [comment]
fixed in https://github.com/openaustralia/righttoknow/compare/e8f5de664169...53c9772a5716

![screen shot 2015-03-16 at 4 05 39 pm](https://cloud.githubusercontent.com/assets/1239550/6660868/85343752-cbf6-11e4-90f6-0490a1b102ef.png)
![screen shot 2015-03-16 at 4 05 48 pm](https://cloud.githubusercontent.com/assets/1239550/6660869/8538e77a-cbf6-11e4-90fd-5891b4baa994.png)

**Comment by henare** [comment]
:metal: I'll deploy the updates to staging now.
