### ISSUE TITLE
Admin bar doesn't wrap properly on mobiles

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#464]
The Admin bar doesn't wrap properly on my iPhone 6 now that responsive styling is enabled:
![ios simulator screen shot 2 apr 2015 10 02 30 pm](https://cloud.githubusercontent.com/assets/6841582/6962824/3060bca0-d984-11e4-84ed-546f3fd54209.png)

The Admin console also isn't responsive at all:
![ios simulator screen shot 2 apr 2015 10 04 46 pm](https://cloud.githubusercontent.com/assets/6841582/6962838/55e2691a-d984-11e4-9808-3218350b03ee.png)

**Comment by equivalentideas** [comment]
Thanks @brfairless 

There are two separate issues here:
1. The admin bar on the front end doesn't change layout for smaller screens
2. The admin views don’t adapt for smaller screen use at all

@ben Are you happy if we keep this issue about no.1 and if you think no.2 is a problem break it out into it's own issue?

**Comment by equivalentideas** [comment]
@brfairless because this is development for the small number of admin users, can you document here current problem and why it would be useful to adapt the admin bar for them?

For example, are you unable to access some of the links that you need to administer the site? Does it break the layout of the site in a way that makes it hard to access some other functionality?

Unless it's currently blocking admins in some way I think this is relatively low priority.

**Comment by benrfairless** [comment]
I tend to do admin stuff on my phone and I can't get some of the buttons, so I would say this is a minor issue, if it can be fixed quickly then great, if not then ahh well:

## 

Ben Fairless
Right to Know Volunteer

e: ben@rightotknow.org.au
w: www.rightotknow.org.au
t: @RighttoKnowAu

**Comment by equivalentideas** [comment]
> I tend to do admin stuff on my phone and I can't get some of the buttons

That's really helpful, would be really good to include that kind of thing in issue descriptions :)

I'll have a look at how much time this would take and we can go from there.

**Comment by henare** [comment]
Closing since this is open upstream.
