### ISSUE TITLE
After sharing a request via twitter, users are prompted to follow alaveteli_foi

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#517]
Should we be prompting users to follow alaveteli_foi after sharing requests via Twitter?

**Comment by equivalentideas** [comment]
I'm assuming this issue is about changing that to use the account for Right To Know https://twitter.com/RightToKnowAu instead.

**Comment by equivalentideas** [comment]
I think this is because of the 'related' data being pushed to twitter ([see twitter dev docs](https://dev.twitter.com/web/tweet-button)):

> Twitter may suggest accounts to follow after the author has successfully posted a Tweet. These displayed accounts are influenced by the `via` and `related` web intent parameters.

It used to mention the 'alaveteli_foi' account:
https://github.com/mysociety/alaveteli/commit/7c92fb67028c0371b796cd26edabe9a905d47561#diff-169f058dcf4853f01eb90de23d0a25f6R4

It now mentions mySocietyInt in our version (another depreciated account) and the current mySociety account in the latest Alaveteli version:
https://github.com/mysociety/alaveteli/blob/develop/app/views/request/_act.html.erb#L8

I think this is fine to leave. @RightToKnowAu is the `via` account, which also impacts follow recommendations. And people who share may well be interested in other mysoc stuff. It's not currently configurable through alaveteli, so we could override the partial and make it about OpenAustralia Foundation, but I don't think it's worth bothering.

I’m gonna close this, please reopen if you think changing this will be helpful to people :)
