### ISSUE TITLE
Follow up reason highlight has gone missing

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#537]
When writing a follow up message there's a section under the heading "What are you doing?" that has a couple of options for the person to choose from. I'm pretty certain this had a red highlight box around it that's gone missing.

**Comment by equivalentideas** [comment]
## Now

![screen shot 2016-08-10 at 3 59 12 pm](https://cloud.githubusercontent.com/assets/1239550/17543354/7b6f5420-5f13-11e6-9fbc-6ec497771d54.png)

## Before

![screen shot 2016-08-10 at 4 07 34 pm](https://cloud.githubusercontent.com/assets/1239550/17543535/a194f050-5f14-11e6-96a4-ea1322c9f9c4.png)

[The red background colour was removed](https://github.com/openaustralia/righttoknow/commit/23d262e28c337f5656daa13f1786eab2a9cb2923) when we updated our form styles as part of moving to the responsive theme:

> **remove background colour from input fields with errors (css only)**
> This removes a red background colour added to a span that wraps
> erroring input fields. As we're now using a top-aligned input/label
> pattern, this background colour style is no[t] effective.
> 
> Removing the background colour puts our error style in line with the
> Alaveteli default.

It clearly impacted this form as well, because even though there is no error the class was being used to make this really prominent with the red colour I guess.

This was unintentional, but the question is “this a regression for users?”. I don't think so, and if the purpose is to make sure they submit it, isn't it simpler for users to just make that input required? I think the error colour suggests something is wrong, rather than you should fill this out.

You do you recon @henare ?

**Comment by henare** [comment]
> This was unintentional, but the question is “this a regression for users?”. I don't think so...

@equivalentideas how about putting forward the reasons for this element's removal like you would in a pull request? That would make it really clear why we think this should be changed.

**Comment by equivalentideas** [comment]
> @equivalentideas how about putting forward the reasons for this element's removal like you would in a pull request?

I think that style should be removed because it's inconsistent with our error style, in that it applies our form error style for a case when there's no error. This dilutes the meaning of our red error colour.

The background colour is also trying to make people see this selection input, but it is already very clear. It has a bit heading (a question) and is right above the submit button with lots of white space around. It's not competing with other elements in a way that would warrant calling more attention to it. If a user does miss this question, the form wont submit and they get an error asking them to select an option. So there is no risk of users not filling this in, which would require a red warning colour.

I think removing this is a small win for users sending followup messages and we should close this.

**Comment by henare** [comment]
Very nice :ok_hand:
