### ISSUE TITLE
Request categorisation scoreboard has odd borders

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#539]
Compare:
- https://www.righttoknow.org.au/categorise/play
- http://www.whatdotheyknow.com/categorise/play

I think it's because of the borders I added to tables for the request cost tables in the help section.

**Comment by equivalentideas** [comment]
> I think it's because of the borders I added to tables for the request cost tables in the help section.

That’s correct 3f2571ad , the table styles there apply to all tables through the site. That doesn't seem to be having a bad impact at the moment as we probably don't have many tables.

I think the right thing to do would be remove the styles for this specific table.

@henare I found the title of this issue a bit confusing: is it odd that the table has borders at all, or is there something odd about the style of the borders. Looking at the wdtk version I decided you probably meant there shouldn't be borders—but would have saved the confusion to just say something like that ;-)

**Comment by equivalentideas** [comment]
@henare is this how you remember this table looking?

![screen shot 2016-08-08 at 9 27 07 am](https://cloud.githubusercontent.com/assets/1239550/17466093/5cf0e830-5d4a-11e6-82ea-60c67db0d9ab.png)

That matches the style of WhatDoTheyKnow (though there larger site-wide `line-height`makes it a bit nicer):

![screen shot 2016-08-08 at 9 28 26 am](https://cloud.githubusercontent.com/assets/1239550/17466097/7efc753e-5d4a-11e6-842e-d78357a4a294.png)

I think ours is actually clearer with the borders (aside from the extra cell, but [I've submitted a fix upstream](https://github.com/mysociety/alaveteli/pull/3444)). But I think this issue is about returning it to it's intended state, and if we want we could open another issue to improve the readability of this table, though I suspect that's not a high priority.

If i'm correct about what this is about @henare , then I can do the fix quick smart.

**Comment by henare** [comment]
@equivalentideas that all sounds good. Please go ahead and implement this :+1:
