### ISSUE TITLE
Sign in error box missing right padding

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#583]
Makes it looks squished:

![selection_001](https://cloud.githubusercontent.com/assets/48945/17353032/1dc0e4cc-597f-11e6-8a53-543dcd3e85b6.png)

**Comment by equivalentideas** [comment]
Fixed by https://github.com/openaustralia/righttoknow/compare/b4d5d107b2a6...239bc63ffb31

![screen shot 2016-08-08 at 8 22 22 am](https://cloud.githubusercontent.com/assets/1239550/17465651/525e8552-5d41-11e6-8d79-32eca186b1e9.png)
![screen shot 2016-08-08 at 8 22 35 am](https://cloud.githubusercontent.com/assets/1239550/17465652/525fed7a-5d41-11e6-8d02-c1880ee31f74.png)
![screen shot 2016-08-08 at 8 22 46 am](https://cloud.githubusercontent.com/assets/1239550/17465653/5262e110-5d41-11e6-8096-04fa06dcfc92.png)
