### ISSUE TITLE
Hidden requests still show in "Similar requests"

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/righttoknow#726]
In the linked discussion, we've hidden some requests as they aren't within the terms of the site.

However, they're still showing in the "Similar requests" sidebar. 

This issue is opened to track this specific incident. This maybe be a recurrence of the issue described in #295 or #313, or may be related to mysociety/alaveteli/issues/728.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1re11)

**Comment by benrfairless** [comment]
I think we should focus on updating the code base on the site before we look into this. 

—
Ben Fairless

OpenAustralia Foundation

openaustralia | planningalerts | electionleaflets | righttoknow | theyvoteforyou | morph

--- original message ---
On 14 November 2019, 8:43 am AWST notifications@github.com wrote:


In the linked discussion, we've hidden some requests as they aren't within the terms of the site.

However, they're still showing in the "Similar requests" sidebar.

This issue is opened to track this specific incident. This maybe be a recurrence of the issue described in #295 or #313, or may be related to #728.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by jamezpolley** [comment]
I think we should look at updating the codebase on the site before we try to fix this permanently, but right now I'd like to fix the current problem

**Comment by jamezpolley** [comment]
#295 and #313 have mostly talked about xapian indexes or varnish caching. mysociety/alaveteli/issues/728 mentions rails caching, but only to say that upstream alaveteli didn't use it at the time.

However, in this case, updating xapian indexes didn't seem to do anything. The varnish cache purging *seems* to be set up correctly, I think. In any case, I was seeing the stale content as a logged-in user, and varnish shouldn't be handling requests for logged-in users.

In this case, the issue seems to have been Rails caching the snippet used for the "Similar requests" sidebar. I'm not sure if this indicates that upstream alaveteli changed since mysociety/alaveteli/issues/728 or if it's something we've added.

I was able to run:
````
deploy@ip-172-31-43-31:/srv/www/production/current$ RAILS_ENV=production bundle exec rails console
Loading production environment (Rails 3.2.22.3)
irb(main):002:0> Rails.cache.clear
=> [<MemCache::Server: localhost:11211 [1] (CONNECTED)>]
irb(main):003:0>
````

On the next page request, both logged in and anonymous, the sidebar was updated.

**Comment by jamezpolley** [comment]
I'm going to close this issue now as the particular operational issue discussed here seems to be resolved.
