### ISSUE TITLE
I’m not getting summary emails

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#769]
I'm not getting summary emails about requests or agencies I'm following.

I am getting emails about my requests which are overdue, so some emails are going out. 

I suspect this is a cron job not working properly following the upgrades.

**Comment by mlandauer** [comment]
Looks to me like I missed some updates that needed to be done to the cron jobs. I guess that wasn't documented in the upgrade notes. :-( Thanks for spotting this @benrfairless.

**Comment by benrfairless** [comment]
Sorry @mlandauer re-opening this. I'm still not getting daily updates. 

I'm subscribed to a number of requests and authorities and none have come through.

**Comment by mlandauer** [comment]
I guess I shouldn't be surprised it didn't work first go. Thanks @benrfairless for re-opening the issue. I'll take a look now.

**Comment by mlandauer** [comment]
I think I completely misunderstood one bit of the upgrade notes. I thought a new notifications thing was replacing the "tracking" but I don't think that's the case. I've reinstated the old daemon https://github.com/openaustralia/infrastructure/commit/654715334f37c0a01bfb1cd0328fbcd69fd31c1e. Please let me know if that makes any difference @benrfairless

**Comment by benrfairless** [comment]
I'm still not getting the daily notification emails :(

**Comment by mlandauer** [comment]
@benrfairless According to https://www.righttoknow.org.au/admin/users/487 where it says  "Last daily track email" it seems to suggest you received one on March 2nd (yesterday). Is there any chance that you received an email but it's gone into spam or something like that?

**Comment by mlandauer** [comment]
On closer examination that "last daily track email" date gets updated even if no actual email gets sent out (because there's nothing to notify you about). It basically suggests that the last time things were checked whether you should receive something was yesterday. So, that at least looks promising.

Looking at [the code](https://github.com/mysociety/alaveteli/blob/0.38.4.0/app/mailers/track_mailer.rb#L54) a little more closely it also looks like even if you haven't received an email in a while it won't send you anything unless the thing tracked has been updated in the last week.

See the comment in the code:
> If the alerts break for a whole week, then they will miss some items. Tough.

Any chance @benrfairless that this fits your situation?

**Comment by mlandauer** [comment]
By the way I checked the logs for the daemon and there's nothing in them other than a message saying the daemon started. Also, I checked that the daemon is currently running which it is.

**Comment by benrfairless** [comment]
I removed and re-added the thing I was following and it now appears to be working. That said, I had a lot of things I was following so maybe I hit a limit somewhere. Going to close this off.
