### ISSUE TITLE
House Rules - Be clearer about the consequences

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#782]
From Matt's comment here: https://github.com/openaustralia/righttoknow/pull/780#issuecomment-789275653

> So if someone is breaking the house rules irrespective of when a comment or request was made you can exercise your judgement on how to deal with that - if that's banning someone or hiding a request/comment or writing to them to ask them to change their behaviour.

Should we update the house rules to update the fact that there are multiple courses of action?

**Comment by benrfairless** [comment]
Instead of:
> If you break any of the rules we will likely suspend your account.

I'm thinking something like:
> If you break any of the rules there are a number of actions we may take. These include removing your request/annotation, or reminding you of our house rules. In more serious or repeated cases, we will likely suspend your account.

**Comment by mlandauer** [comment]
I think the suggested wording is good. It makes it clearer that there are a number of potential consequences and that we will make a judgement call based on the seriousness of the "violation". I think it's good that it doesn't lay out a specific process because I'm a little wary that that potentially could be used against us by users of the site with bad intentions.
